service: aws-cemaritan-api

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python3.6

functions:
  get_connections:
    handler: connection.connections
    events:
      - http:
        path: connections
        method: get

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux