service: aws-cemaritan-api

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python3.6
  memorySize: 512
  stage: dev
  region: us-east-1
  environment:
    DB_HOST: ${ssm:host} 
    PORT: ${ssm:port}
    DB_NAME: ${ssm:dbname}
    USER: ${ssm:user}
    PASSWORD: ${ssm:pw}

functions:
  # This will only be used by some Cemaritan level admin
  get_organizations:
    handler: organization.organizations
    events:
      - http:
          path: organizations
          method: get
          cors: true

  # Collections functions
  get_connections:
    handler: connection.connections
    events:
      - http:
          path: organizations/{organization_id}/connections
          method: get
          cors: true
          request:
            parameters:
              paths:
                organization_id: true
  get_mappings:
    handler: mapping.mappings
    events:
      - http:
          path: organizations/{organization_id}/mappings
          method: get
          cors: true
          request:
            parameters:
              paths:
                organization_id: true

  get_transfers:
    handler: transfer.transfers
    events:
      - http:
          path: organizations/{organization_id}/transfers
          method: get
          cors: true
          request:
            parameters:
              paths:
                organization_id: true
  get_users:
    handler: user.users
    events:
      - http:
          path: organizations/{organization_id}/users
          method: get
          cors: true
          request:
            parameters:
              paths:
                organization_id: true
  get_histories:
    handler: history.histories
    events:
      - http:
          path: organizations/{organization_id}/histories
          method: get
          cors: true
          request:
            parameters:
              paths:
                organization_id: true
                
  # Single object functions
  transfer:
    handler: transfer.transfer
    events:
      - http:
          path: organizations/{organization_id}/transfers/{transfer_id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                organization_id: true
                transfer_id: true
      - http:
          path: organizations/{organization_id}/transfers/{transfer_id}
          method: post
          cors: true
          request:
            parameters:
              paths:
                organization_id: true
                transfer_id: true

    
plugins:
  - serverless-python-requirements
  - serverless-package-external

custom:
  pythonRequirements:
    dockerizePip: non-linux
  packageExternal:
    external:
      - '../models'
      - '../library'