service: aws-python-convert-record

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python3.6

functions:
  convertsingle:
    handler: conversion.convertsingle
    events:
      - http:
          path: convertsingle
          method: post
  convertbulk:
    handler: conversion.convertbulk
    events:
      - http:
          path: convertbulk
          method: post
